pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh './scripts/build-image.sh'
            }
        }

        stage('Load Image into Kind') {
            steps {
                sh './scripts/load-kind.sh'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh './scripts/deploy.sh'
            }
        }
    }

    post {
        success {
            echo 'CloudDeploy Platform deployed successfully!'
        }

        failure {
            echo 'Deployment failed!'
        }
    }
}
