apiVersion: v1
kind: ConfigMap

metadata:
  name: clouddeploy-config
  namespace: {{ .Values.namespace }}

data:

  APP_NAME: "{{ .Values.config.appName }}"

  ENVIRONMENT: "{{ .Values.config.environment }}"

  VERSION: "{{ .Values.config.version }}"
