apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}

  labels:
    app: {{ .Values.app.label }}

spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.app.label }}

  template:

    metadata:
      labels:
        app: {{ .Values.app.label }}

    spec:

      containers:

        - name: {{ .Values.app.containerName }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:

            - containerPort: {{ .Values.service.targetPort }}

          envFrom:

            - configMapRef:
                name: clouddeploy-config

            - secretRef:
                name: clouddeploy-secret

          env:

            - name: BUILD_NUMBER
              value: "{{ .Values.config.buildNumber }}"

            - name: GIT_COMMIT
              value: "{{ .Values.config.gitCommit }}"

          readinessProbe:

            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.targetPort }}

            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:

            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.targetPort }}

            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          resources:

            requests:

              cpu: {{ .Values.resources.requests.cpu }}

              memory: {{ .Values.resources.requests.memory }}

            limits:

              cpu: {{ .Values.resources.limits.cpu }}

              memory: {{ .Values.resources.limits.memory }}
