apiVersion: v1
kind: Secret

metadata:
  name: clouddeploy-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  DB_USERNAME: "{{ .Values.secret.dbUsername }}"

  DB_PASSWORD: "{{ .Values.secret.dbPassword }}"
