apiVersion: v1
kind: Secret

metadata:
  name: clouddeploy-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  DB_USERNAME: {{ .Values.secret.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
